### ISSUE TITLE
Make app work on Android devices without a PIN

### ISSUE THREAD

**Issue by andywer** [satoshipay/solar#713] opened 2019-08-29 08:12 UTC
There was an issue with the Android key store or the cordova plugin we use that prevents us from using the Android key store if the user did not set a device PIN, as that PIN is used to derive a key store secret...

Turns out quite a large percentage of Android users don't have a PIN set and we cannot just ignore them. Let's find a solution!

**Comment by Marcel-Ebert** [comment] 2019-08-29 14:09
I did some research on this and it seems like the lock screen setup is only required if [KeyPairGeneratorSpec.setEncryptionRequired()](https://developer.android.com/reference/android/security/KeyPairGeneratorSpec.Builder.html#setEncryptionRequired()) is set during keypair generation.

The `cordova-plugin-secure-storage` does exactly this.
It makes sense that they restrict the usage so that it only works if a lock screen is set because if you try generating a key pair with `setEncryptionRequired()` and no screen lock is set up, then the generation of the key pair fails with an exception (as is described [here](https://doridori.github.io/android-security-the-forgetful-keystore/#sthash.0tNjwTWs.KbFqeBuv.dpbs)).

So I think we could still use the plugin the way it is now, but enhance it so that if the user has no lock screen set, we don't call `setEncryptionRequired()` during key pair generation and it should work just fine.
Have to test it out though.

And I can't really tell what this means security-wise.
The Android-documentation states that `setEncryptionRequired()`:
> Indicates that this key pair must be encrypted at rest. This will protect the key pair with the secure lock screen credential (e.g., password, PIN, or pattern).

But since the key pair is stored with the Android keystore system, it shouldn't be easily accessible anyways.

**Comment by Marcel-Ebert** [comment] 2019-08-29 15:40
OK so I made some changes to the android code of the plugin and it works now without requiring a set lock screen.
I changed it the way I mentioned before so the `setEncryptionRequired()` is only set if the device is "secure". 

One thing I noticed was that if I want to enable the "Fingerprint lock" feature flag in settings, the app errors with message "Keystore operation failed".
The message of the exception is:
```
android.security.KeyStoreException: User authentication required
```
and the exception is thrown because `setUserAuthenticationRequired(true)` is set during key generation for the fingerprint-plugin (which uses the android keystore system as well).

We could either remove that line or check whether the device is secure before calling those methods.
Or even simpler we just check the error message and if it contains that message we assume that it's because the user has no lock screen set and show a different error message.

**Comment by Marcel-Ebert** [comment] 2019-08-30 14:36
During my testing I noticed that the wallets data will be "wiped" or rather inaccessible in the following scenario:

1. The user starts the application for the first time when he has a lock screen set.
2. The application will generate a key pair with `setEncryptionRequired()` and store it in the Android keystore system. 
3. If he changes his lock screen method to "None" or "Swipe" the data will be inaccessible because the device is not secure anymore. The app will appear as on first start when he opens it the next time.

This is expected behaviour and described [here](https://developer.android.com/reference/android/security/KeyPairGeneratorSpec.Builder.html#setEncryptionRequired()).
To prevent this we could just **never** use `setEncryptionRequired()` and it won't matter if the user changes his lock screen method.
@andywer please let me know what you think about this.

**Comment by andywer** [comment] 2019-08-30 14:47
@Marcel-Ebert Let's ditch `setEncryptionRequired()`!

> setEncryptionRequired() was deprecated in Android 6.0 (Marshmallow), and never really accomplished very much. The security of Android KeyStore depends on the TEE, not the password.

See <https://stackoverflow.com/a/43422782>.

**Closed** 2019-08-30 15:38 UTC
Labels: platform: cordova, research, tech story
