### ISSUE TITLE
Windows thinks Solar is malicious software

### ISSUE THREAD

**Issue by erasmus** [satoshipay/solar#354] opened 2019-01-21 12:54 UTC
Device/OS: Windows10 , Chrome/Edge

## To replicate
- I download the .exe file from https://github.com/satoshipay/solar/releases/download/v0.15.0/Solar.Wallet.Setup.0.15.0.exe via Chrome
- An error message pops out and says "...exe file is not normally downloaded and can be dangerous." After approving the download, it says "failed" because "virus detected". The file cannot be downloaded
- Even if you use Edge to download it, Windows Defender Smartscreen blocks the installation. You can then choose "More info" and click "run anyway", but the option is not obvious.

![image_ 2](https://user-images.githubusercontent.com/1915920/51475905-195e2680-1d84-11e9-8d64-3bb687539766.png)
![image_ 3](https://user-images.githubusercontent.com/1915920/51475906-19f6bd00-1d84-11e9-8789-fe99e01a6608.png)

**Comment by andywer** [comment] 2019-01-21 17:16
True, unfortunately, but also a duplicate of #351.

For everyone: We are actively working on it and it should be fixed within a few days. The warning is also misleading. The windows defender basically shows this message for any unsigned electron app.

Keeping it open, so the next people running into it can read this.

**Comment by andywer** [comment] 2019-04-11 07:34
Already fixed.

**Closed by andywer** 2019-04-11 07:34 UTC
Labels: bug
