### ISSUE TITLE
Import of secret key does not work

### ISSUE THREAD

**Issue by AlessandroM92** [satoshipay/solar#1177] opened 2020-11-30 19:28 UTC
Hi folks,

in version 0.25.3 I cannot import my secret key. When I press the "Import Account" button nothing happens.

BR
Alessandro

**Comment by ebma** [comment] 2020-12-02 08:45
Hi @AlessandroM92, which platform are you using? I'm not able to reproduce this, is there any error shown above or below the textfields?

**Comment by AlessandroM92** [comment] 2020-12-02 09:24
I use the wallet on Windows 10. There are no errors shown.

**Comment by ebma** [comment] 2020-12-02 12:36
Please try opening the developer console by pressing `F12` or `CTRL+SHIFT+i` and see if clicking on the "Import Account" button will print an error message to the console. (Make sure the 'console' tab is selected after you opened the developer tools window).

**Comment by AlessandroM92** [comment] 2020-12-03 14:40
I actually get the following error: 

```
Uncaught Error: invalid checksum
    at k (bootstrap.541f4c3a.js:1011)
    at Function.value (bootstrap.541f4c3a.js:1011)
    at Function.value (bootstrap.541f4c3a.js:1014)
    at l (app-stage2.cec4b0ac.js:116)
    at f (app-stage2.cec4b0ac.js:116)
    at validateAccountCreation (app-stage2.cec4b0ac.js:116)
    at app-stage2.cec4b0ac.js:470
    at Object.l (bootstrap.541f4c3a.js:264)
    at s (bootstrap.541f4c3a.js:264)
    at f (bootstrap.541f4c3a.js:264)
```


```
k | @ | bootstrap.541f4c3a.js:1011
-- | -- | --
  | value | @ | bootstrap.541f4c3a.js:1011
  | value | @ | bootstrap.541f4c3a.js:1014
  | l | @ | app-stage2.cec4b0ac.js:116
  | f | @ | app-stage2.cec4b0ac.js:116
  | validateAccountCreation | @ | app-stage2.cec4b0ac.js:116
  | (anonymous) | @ | app-stage2.cec4b0ac.js:470
  | l | @ | bootstrap.541f4c3a.js:264
  | s | @ | bootstrap.541f4c3a.js:264
  | f | @ | bootstrap.541f4c3a.js:264
  | h | @ | bootstrap.541f4c3a.js:264
  | st | @ | bootstrap.541f4c3a.js:264
  | ut | @ | bootstrap.541f4c3a.js:264
  | ft | @ | bootstrap.541f4c3a.js:264
  | vt | @ | bootstrap.541f4c3a.js:264
  | R | @ | bootstrap.541f4c3a.js:264
  | A | @ | bootstrap.541f4c3a.js:264
  | ln | @ | bootstrap.541f4c3a.js:264
  | rn | @ | bootstrap.541f4c3a.js:264
  | exports.unstable_runWithPriority | @ | bootstrap.541f4c3a.js:260
  | ri | @ | bootstrap.541f4c3a.js:264
  | F | @ | bootstrap.541f4c3a.js:264
  | tn | @ | bootstrap.541f4c3a.js:264
```



`

**Comment by ebma** [comment] 2020-12-07 10:01
Okay now I was able to reproduce your issue by exchanging one letter in a valid secret key with a random one.
Did you maybe mix up the letters `O` with the number `0` at some point? Also the key is case sensitive so you should only use capital letters.

**Comment by AlessandroM92** [comment] 2020-12-10 18:58
I'm quite sure my secrect key should be ok. 
One thing to mention: my key is a few years old. Can that have anything to do with the problem? I created it with another wallet.

**Comment by ebma** [comment] 2020-12-14 09:20
Hmm keys should not become invalid over time. It could be that the other wallet is offering you something for backup/ restoring that is only derived from your secret key but I guess that's rather unlikely. 
So just to be clear: `SAV76USXIJOBMEQXPANUOQM6F5LIOTLPDIDVRJBFFE2MDJXG24TAPUU7` is an example of a valid secret key, starts with the letter `S` and has 56 characters. If your secret key is similar to this I honestly don't know what else could be the reason here. I improved the secret key check so in the next release you would at least get an error message if the import fails due to an invalid checksum.

**Comment by AlessandroM92** [comment] 2020-12-21 06:02
Thanks for the advice. I will give it another try.

**Comment by andywer** [comment] 2021-01-09 16:34
Closing. We will release a new version in the next few days.

Feel free to re-open if you still encounter issues after the update.

**Closed by andywer** 2021-01-09 16:34 UTC
